CC=$(CXX)


OPTIONS := -fPIC 
ARCH_FLAGS := -mepi
EXTRA_C_FLAGS := -O3 ${ARCH_FLAGS}  -std=c++17 ${OPTIONS}



include Makefile.objs

LIB_OBJS+= ConvRVVImpl.o

ConvRVVImpl.o: src/layers/core/Conv_rvv_impl.cc include/emptyNN/layers/core/Conv_rvv_impl.hpp
	$(CC) -c ${EXTRA_C_FLAGS} $(CFLAGS) ${INCL_FLAGS} src/layers/core/Conv_rvv_impl.cc -o ConvRVVImpl.o

rvvnet: examples/rvv_net.cc ${LIB_OBJS}
	$(CC) ${EXTRA_C_FLAGS} $(CFLAGS) ${INCL_FLAGS} ${LIB_OBJS} examples/rvv_net.cc -o rvvnet.exe
